spring:
  application:
    name: backupmanager

storage:
  s3:
    endpoint: http://localhost:9000
    bucket-name: erp-backups-market
    region: us-east-1
    access-key: minioadmin
    secret-key: minioadmin